from __future__ import annotations

import contextlib
import io
import json
import tempfile
import unittest
from pathlib import Path
from threading import Event

import trimesh

from ai_print_optimizer.cli import main
from ai_print_optimizer.report import PrintSettings
from ai_print_optimizer.slicer_backend import INDEPENDENT_BACKEND
from ai_print_optimizer.vanior_slice import (
    VaniorSliceError,
    _choose_support_strategy,
    _motion_time_s,
    _simplify_toolpath,
    slice_stl_to_gcode,
)


def _settings(*, supports: bool = False, brim: bool = False) -> PrintSettings:
    return PrintSettings(
        layer_height_mm=0.2,
        wall_loops=2,
        top_layers=4,
        bottom_layers=4,
        supports=supports,
        brim=brim,
        nozzle_temperature_c=220,
        bed_temperature_c=55,
        fan_percent=100,
        sparse_infill_percent=15,
        outer_wall_speed_mm_s=80,
        inner_wall_speed_mm_s=120,
        sparse_infill_speed_mm_s=120,
        internal_solid_infill_speed_mm_s=100,
        initial_layer_speed_mm_s=40,
        travel_speed_mm_s=300,
        max_volumetric_speed_mm3_s=21.0,
    )


class VaniorSliceTests(unittest.TestCase):
    def test_dense_subresolution_path_is_simplified(self) -> None:
        path = [(index * 0.001, (index % 2) * 0.001) for index in range(101)]

        simplified = _simplify_toolpath(path)

        self.assertLess(len(simplified), len(path) // 4)
        self.assertEqual(simplified[0], path[0])
        self.assertEqual(simplified[-1], path[-1])

    def test_motion_estimate_accounts_for_acceleration(self) -> None:
        self.assertGreater(_motion_time_s(0.05, 100.0, 5_000.0), 0.05 / 100.0)

    def test_high_removal_risk_rejects_cheaper_normal_supports(self) -> None:
        normal = {
            "strategy": "normal",
            "eligible": True,
            "estimated_support_time_s": 10.0,
            "estimated_support_mass_g": 1.0,
        }
        tree = {
            "strategy": "tree",
            "eligible": True,
            "estimated_support_time_s": 30.0,
            "estimated_support_mass_g": 2.0,
        }

        selected, reason, candidates = _choose_support_strategy(
            "auto",
            _settings(supports=True),
            normal,
            tree,
            demand_area_mm2=50.0,
            support_exit_risk="HIGH",
            support_accessibility_score=4.0,
        )

        by_name = {item["strategy"]: item for item in candidates}
        self.assertEqual(selected, "tree")
        self.assertFalse(by_name["normal"]["eligible"])
        self.assertIn("4/100", reason)

    def test_independent_backend_slices_box_and_passes_audit(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "box.stl"
            output = root / "box.gcode"
            trimesh.creation.box(extents=(20.0, 20.0, 4.0)).export(source)
            progress_events = []

            result = INDEPENDENT_BACKEND.slice_stl(
                source,
                output,
                _settings(),
                material="PLA",
                nozzle_diameter_mm=0.4,
                progress_callback=progress_events.append,
                cancel_event=Event(),
            )

            self.assertTrue(INDEPENDENT_BACKEND.independent)
            self.assertEqual(result.engine, "VANIOR Slice")
            self.assertEqual(result.engine_stage, "engineering-preview")
            self.assertGreaterEqual(result.layer_count, 19)
            self.assertGreater(result.line_count, 100)
            self.assertGreater(result.estimated_mass_g, 0)
            self.assertNotEqual(result.audit.status, "BLOCKED")
            self.assertTrue(progress_events)
            self.assertEqual(progress_events[-1].percent, 100)
            text = output.read_text(encoding="utf-8")
            self.assertIn("generated by VANIOR Slice", text)
            self.assertNotIn("BambuStudio", text)
            self.assertIn("minimum layer time", text)
            self.assertGreaterEqual(
                result.audit.shortest_estimated_layer_time_s or 0.0,
                2.0,
            )
            self.assertFalse(
                any(
                    "быстрых слоя" in warning
                    for warning in result.audit.advisory_warnings
                )
            )

    def test_normal_supports_are_generated_under_a_large_overhang(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "supported-t.stl"
            output = root / "supported-t.gcode"
            post = trimesh.creation.box(extents=(4.0, 4.0, 10.0))
            post.apply_translation((0.0, 0.0, 5.0))
            cap = trimesh.creation.box(extents=(20.0, 20.0, 2.0))
            cap.apply_translation((0.0, 0.0, 11.0))
            trimesh.util.concatenate((post, cap)).export(source)

            result = slice_stl_to_gcode(
                source,
                output,
                _settings(supports=True),
            )

            self.assertNotEqual(result.audit.status, "BLOCKED")
            text = output.read_text(encoding="utf-8")
            self.assertIn("; FEATURE: SUPPORT\n", text)
            self.assertIn("; FEATURE: SUPPORT-INTERFACE\n", text)
            support_section = text.split("; FEATURE: SUPPORT\n", 1)[1].split(
                "; FEATURE: SUPPORT-INTERFACE\n", 1
            )[0]
            self.assertIn(" E", support_section)

    def test_separated_components_may_have_empty_intermediate_layers(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "separated-components.stl"
            lower = trimesh.creation.box(extents=(8.0, 8.0, 2.0))
            lower.apply_translation((0.0, 0.0, 1.0))
            upper = trimesh.creation.box(extents=(8.0, 8.0, 2.0))
            upper.apply_translation((0.0, 0.0, 9.0))
            trimesh.util.concatenate((lower, upper)).export(source)

            result = slice_stl_to_gcode(
                source,
                root / "separated.gcode",
                _settings(supports=True),
                support_exit_risk="HIGH",
                support_accessibility_score=10.0,
            )

            self.assertGreater(result.layer_count, 40)
            self.assertEqual(result.support_strategy, "tree")
            self.assertGreater(result.estimated_support_mass_g, 0)

    def test_auto_supports_compare_all_strategies_and_choose_lowest_cost(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "support-comparison.stl"
            post = trimesh.creation.box(extents=(4.0, 4.0, 10.0))
            post.apply_translation((0.0, 0.0, 5.0))
            cap = trimesh.creation.box(extents=(20.0, 20.0, 2.0))
            cap.apply_translation((0.0, 0.0, 11.0))
            trimesh.util.concatenate((post, cap)).export(source)

            result = slice_stl_to_gcode(
                source,
                root / "auto.gcode",
                _settings(supports=True),
                support_strategy="auto",
            )

            candidates = {item["strategy"]: item for item in result.support_candidates}
            self.assertEqual(set(candidates), {"none", "normal", "tree"})
            self.assertFalse(candidates["none"]["eligible"])
            expected = min(
                ("normal", "tree"),
                key=lambda name: float(candidates[name]["score"]),
            )
            self.assertEqual(result.support_strategy, expected)
            self.assertTrue(candidates[expected]["selected"])
            self.assertGreater(result.estimated_support_mass_g, 0)
            text = result.gcode_path.read_text(encoding="utf-8")
            self.assertIn(f"; support_strategy={expected}", text)
            self.assertIn("; FEATURE: SUPPORT", text)

    def test_tall_support_job_reports_bounded_monotonic_progress(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "tall-support.stl"
            post = trimesh.creation.box(extents=(4.0, 4.0, 40.0))
            post.apply_translation((0.0, 0.0, 20.0))
            cap = trimesh.creation.box(extents=(20.0, 20.0, 2.0))
            cap.apply_translation((0.0, 0.0, 41.0))
            trimesh.util.concatenate((post, cap)).export(source)
            progress_events = []

            result = slice_stl_to_gcode(
                source,
                root / "tall-support.gcode",
                _settings(supports=True),
                progress_callback=progress_events.append,
                cancel_event=Event(),
            )

            percents = [event.percent for event in progress_events]
            support_events = [
                event
                for event in progress_events
                if event.stage.startswith("vanior-support")
            ]
            self.assertEqual(result.layer_count, 210)
            self.assertEqual(percents, sorted(percents))
            self.assertLess(len(progress_events), 100)
            self.assertLess(len(support_events), 20)
            self.assertEqual({event.percent for event in support_events}, set(range(44, 56)))

    def test_auto_supports_reject_unnecessary_supports_for_box(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "box.stl"
            trimesh.creation.box(extents=(12.0, 12.0, 3.0)).export(source)

            result = slice_stl_to_gcode(
                source,
                root / "box.gcode",
                _settings(supports=False),
                support_strategy="auto",
            )

            self.assertEqual(result.support_strategy, "none")
            self.assertEqual(len(result.support_candidates), 3)
            self.assertEqual(result.estimated_support_mass_g, 0)
            self.assertIn("; support_strategy=none", result.gcode_path.read_text(encoding="utf-8"))

    def test_requested_brim_is_emitted_only_on_the_first_layer(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "brim-box.stl"
            output = root / "brim-box.gcode"
            trimesh.creation.box(extents=(10.0, 10.0, 2.0)).export(source)

            result = slice_stl_to_gcode(source, output, _settings(brim=True))

            self.assertNotEqual(result.audit.status, "BLOCKED")
            text = output.read_text(encoding="utf-8")
            first_layer = text.split(";LAYER:1", 1)[0]
            remaining_layers = text.split(";LAYER:1", 1)[1]
            self.assertIn("; FEATURE: SKIRT-BRIM", first_layer)
            self.assertNotIn("; FEATURE: SKIRT-BRIM", remaining_layers)
            self.assertIn("X122.", first_layer)

    def test_oversize_job_fails_before_output(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "oversize.stl"
            output = root / "oversize.gcode"
            trimesh.creation.box(extents=(300.0, 20.0, 4.0)).export(source)

            with self.assertRaisesRegex(VaniorSliceError, "безопасную область"):
                slice_stl_to_gcode(source, output, _settings())

            self.assertFalse(output.exists())

    def test_independent_cli_returns_audited_json(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "cli-box.stl"
            output = root / "cli-box.gcode"
            trimesh.creation.box(extents=(12.0, 12.0, 3.0)).export(source)
            stdout = io.StringIO()

            with contextlib.redirect_stdout(stdout):
                exit_code = main(
                    [
                        str(source),
                        "--vanior-slice-output",
                        str(output),
                        "--json",
                    ]
                )

            payload = json.loads(stdout.getvalue())
            self.assertEqual(exit_code, 0)
            self.assertEqual(payload["engine"], "VANIOR Slice")
            self.assertEqual(payload["engine_stage"], "engineering-preview")
            self.assertNotEqual(payload["audit"]["status"], "BLOCKED")
            self.assertTrue(output.is_file())


if __name__ == "__main__":
    unittest.main()
