"""VANIOR PRINT geometry analyzer and print-project workspace."""

from .analyzer import AnalysisError, analyze_stl
from .batch import BatchError, BatchItemResult, BatchRunResult, run_batch
from .diagnostics import DiagnosticCheck, DiagnosticReport, run_diagnostics
from .functional_intent import FunctionalIntent, infer_functional_intent
from .gcode_audit import GCodeAudit, audit_gcode
from .geometry_features import (
    GeometryFeatureAnalysis,
    LocalModifierPlan,
    SupportExitPlan,
    analyze_geometry_features,
    build_local_modifier_plan,
    plan_support_exit,
)
from .material_protocol import MaterialProtocolError, settings_for_material
from .optimization_protocol import (
    CandidateEvaluation,
    CandidateSliceMetrics,
    OptimizationCandidate,
    OptimizationPlan,
    QualityOptimizationResult,
    build_optimization_plan,
    evaluate_optimization_plan,
)
from .orientation import (
    OrientationExportResult,
    optimize_orientation,
    orient_stl,
)
from .pipeline import (
    ManifestVerification,
    ObjectOptimizationResult,
    PipelineError,
    PipelineResult,
    run_pipeline,
    verify_manifest,
)
from .print_dna import (
    PrintDNAApplication,
    PrintDNAError,
    PrintDNAKey,
    PrintDNAProfile,
    PrintFeedback,
    apply_print_dna,
    load_print_dna_profile,
    record_print_feedback,
)
from .print_evidence import (
    PhysicalPrintComparison,
    PrintEvidenceError,
    record_physical_comparison,
)
from .profile import (
    ProfileError,
    ProfileValidation,
    SourceProfileAssessment,
    assess_bambu_profile,
    validate_bambu_profile,
)
from .progress import OperationCancelled, ProgressEvent
from .project3mf import (
    ExtractedObjectGeometry,
    ExtractedProjectGeometry,
    ObjectPrintConfiguration,
    PreparedMultiObjectProject,
    PreparedProject,
    Project3MFError,
    ReadyProjectVerification,
    create_bambu_project_from_3mf_objects,
    create_bambu_project_from_stl,
    create_bambu_project_from_stl_objects,
    extract_printable_stl,
    extract_stl_objects,
    verify_ready_project,
)
from .reliability import (
    JobJournal,
    VerifiedSliceCache,
    build_diagnostic_bundle,
    create_application_backup,
    create_backup,
    restore_application_data_backup,
)
from .repair import RepairResult, repair_stl
from .report import AnalysisReport
from .simplification import (
    SimplificationError,
    SimplificationResult,
    simplify_stl,
)
from .slicer import (
    GcodeFeatureMetrics,
    GcodeRoleMetrics,
    SlicerError,
    SliceRunResult,
    SupportComparison,
    analyze_gcode_roles,
    compare_stl_supports,
    compare_supports,
    create_profile_carrier,
    create_support_variant,
    discover_bambu_studio,
    ensure_run_publishable,
    optimize_multi_object_3mf,
    optimize_multi_object_project,
    slice_3mf,
    slice_stl_with_template,
)
from .slicer_backend import INDEPENDENT_BACKEND, SlicerBackend, VaniorSlicerBackend
from .surface_intelligence import (
    SurfaceIntelligence,
    SurfaceRole,
    analyze_surfaces,
    settings_for_surfaces,
)
from .vanior_3mf import (
    Vanior3MFError,
    Vanior3MFVerification,
    create_vanior_gcode_3mf,
    verify_vanior_gcode_3mf,
)
from .vanior_slice import (
    P1S_INDEPENDENT,
    VaniorMachineProfile,
    VaniorSliceError,
    VaniorSliceResult,
    slice_stl_to_gcode,
)
from .version import __version__
from .workspace import (
    WorkspaceLayout,
    append_learning_event,
    ensure_workspace,
    import_model,
    next_project_output,
    next_ready_file,
)

__all__ = [
    "INDEPENDENT_BACKEND",
    "P1S_INDEPENDENT",
    "AnalysisError",
    "AnalysisReport",
    "BatchError",
    "BatchItemResult",
    "BatchRunResult",
    "CandidateEvaluation",
    "CandidateSliceMetrics",
    "DiagnosticCheck",
    "DiagnosticReport",
    "ExtractedObjectGeometry",
    "ExtractedProjectGeometry",
    "FunctionalIntent",
    "GCodeAudit",
    "GcodeFeatureMetrics",
    "GcodeRoleMetrics",
    "GeometryFeatureAnalysis",
    "JobJournal",
    "LocalModifierPlan",
    "ManifestVerification",
    "MaterialProtocolError",
    "ObjectOptimizationResult",
    "ObjectPrintConfiguration",
    "OperationCancelled",
    "OptimizationCandidate",
    "OptimizationPlan",
    "OrientationExportResult",
    "PhysicalPrintComparison",
    "PipelineError",
    "PipelineResult",
    "PreparedMultiObjectProject",
    "PreparedProject",
    "PrintDNAApplication",
    "PrintDNAError",
    "PrintDNAKey",
    "PrintDNAProfile",
    "PrintEvidenceError",
    "PrintFeedback",
    "ProfileError",
    "ProfileValidation",
    "ProgressEvent",
    "Project3MFError",
    "QualityOptimizationResult",
    "ReadyProjectVerification",
    "RepairResult",
    "SimplificationError",
    "SimplificationResult",
    "SliceRunResult",
    "SlicerBackend",
    "SlicerError",
    "SourceProfileAssessment",
    "SupportComparison",
    "SupportExitPlan",
    "SurfaceIntelligence",
    "SurfaceRole",
    "Vanior3MFError",
    "Vanior3MFVerification",
    "VaniorMachineProfile",
    "VaniorSliceError",
    "VaniorSliceResult",
    "VaniorSlicerBackend",
    "VerifiedSliceCache",
    "WorkspaceLayout",
    "__version__",
    "analyze_gcode_roles",
    "analyze_geometry_features",
    "analyze_stl",
    "analyze_surfaces",
    "append_learning_event",
    "apply_print_dna",
    "assess_bambu_profile",
    "audit_gcode",
    "build_diagnostic_bundle",
    "build_local_modifier_plan",
    "build_optimization_plan",
    "compare_stl_supports",
    "compare_supports",
    "create_application_backup",
    "create_backup",
    "create_bambu_project_from_3mf_objects",
    "create_bambu_project_from_stl",
    "create_bambu_project_from_stl_objects",
    "create_profile_carrier",
    "create_support_variant",
    "create_vanior_gcode_3mf",
    "discover_bambu_studio",
    "ensure_run_publishable",
    "ensure_workspace",
    "evaluate_optimization_plan",
    "extract_printable_stl",
    "extract_stl_objects",
    "import_model",
    "infer_functional_intent",
    "load_print_dna_profile",
    "next_project_output",
    "next_ready_file",
    "optimize_multi_object_3mf",
    "optimize_multi_object_project",
    "optimize_orientation",
    "orient_stl",
    "plan_support_exit",
    "record_physical_comparison",
    "record_print_feedback",
    "repair_stl",
    "restore_application_data_backup",
    "run_batch",
    "run_diagnostics",
    "run_pipeline",
    "settings_for_material",
    "settings_for_surfaces",
    "simplify_stl",
    "slice_3mf",
    "slice_stl_to_gcode",
    "slice_stl_with_template",
    "validate_bambu_profile",
    "verify_manifest",
    "verify_ready_project",
    "verify_vanior_gcode_3mf",
]
